services:
  - type: web
    name: road-defect-detector
    env: python
    buildCommand: ""
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
